http:
  enabled: true
  address: 0.0.0.0:${OPS_PORT}
  root_path: /benthos
  debug_endpoints: false
  cert_file: ""
  key_file: ""
  cors:
    enabled: false
    allowed_origins: []
input:
  broker:
    inputs:
      - uw_sql_raw:
          driver: ${DRIVER}
          dsn: ${DSN}
          query: ${QUERY}
    batching:
      count: 100000
      period: 2m
pipeline:
  threads: 1
  processors:
  - uw_parquet:
      dataProductID: ${DATA_PRODUCT_ID}
  - catch:
      - log:
          level: ERROR
          message: "Processing failed due to: ${!error()}"
      - uw_terminate:    
output:
  gcp_cloud_storage:
    bucket: ${GS_BUCKET}
    path: ${DATA_PRODUCT_ID}/${DATA_PRODUCT_ID}-${CREATED_AT}_${!count("files")}.parquet
    content_type: application/octet-stream
    collision_mode: overwrite
    max_in_flight: 1
shutdown_timeout: 20s
